name: aplicativo
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: "^0.12.0"

  # Drawer 
  hidden_drawer_menu: ^3.0.1

  # Device Preview
  device_preview: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Internacioalization  
  intl: 0.18.0

  # HTTP Client
  http: 0.13.4
  firebase_core: ^1.12.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/Logo.png"
  adaptative_icon_background: "#2A936E"
  adaptative_icon_foreground: "assets/image/Logo.png"
 


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets\image\logo.png

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 700